import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
const errors = [];
async function run(width, tag) {
  const ctx = await browser.newContext({ viewport: { width, height: 844 }, deviceScaleFactor: width < 500 ? 2 : 1, isMobile: width < 500, hasTouch: width < 500, locale: 'ja-JP' });
  const page = await ctx.newPage();
  page.on('pageerror', (e) => errors.push(`${tag} pageerror: ${e.message}`));
  const shot = (n) => page.screenshot({ path: `/tmp/shots/admin-${tag}-${n}.png`, fullPage: true });
  await page.goto('http://localhost:3000/admin.html');
  await page.waitForSelector('text=管理画面ログイン');
  await shot('01-login');
  await page.click('summary');
  await page.fill('input[name="token"]', 'dev-emergency-token-123456');
  await page.click('button:has-text("緊急ログイン")');
  await page.waitForSelector('[role=tab]');
  await page.waitForSelector('#app .list, #app .state:not(.loading)');
  await shot('02-attendance');
  const first = page.locator('#app .list .item').first();
  if (await first.count()) { await first.click(); await page.waitForSelector('.modal'); await shot('03-detail'); await page.click('.sheet-head button'); }
  await page.click('[role=tab]:has-text("スタッフ")');
  await page.waitForSelector('text=スタッフを追加');
  await shot('04-staff');
  await page.click('#app .list .item >> nth=0');
  await page.waitForSelector('.modal');
  await shot('05-staff-edit');
  await page.click('.sheet-head button');
  await page.click('[role=tab]:has-text("事業所")');
  await page.waitForSelector('text=事業所を追加');
  await page.click('#app .list .item >> nth=0');
  await page.waitForSelector('.modal');
  await shot('06-location-edit');
  await page.click('.sheet-head button');
  await page.click('[role=tab]:has-text("給与データ")');
  await page.waitForSelector('table, .state:not(.loading)');
  await page.fill('input[type=month]', '2026-10');
  await page.dispatchEvent('input[type=month]', 'change');
  await page.waitForTimeout(800);
  await shot('07-payroll');
  await page.click('[role=tab]:has-text("異常検知")');
  await page.waitForSelector('.state:not(.loading), .list');
  await shot('08-anomalies');
  await page.click('[role=tab]:has-text("設定")');
  await page.waitForSelector('text=設定を保存');
  await page.waitForTimeout(400);
  await shot('09-settings');
  await page.click('[role=tab]:has-text("定期処理")');
  await page.waitForSelector('text=メール送信ログ');
  await shot('10-jobs');
  const w = await page.evaluate(() => document.documentElement.scrollWidth);
  console.log(tag, 'scrollWidth', w);
  await ctx.close();
}
await run(390, 'm');
await run(1280, 'd');
console.log('errors', errors);
await browser.close();
