import { chromium } from 'playwright';
import { execSync } from 'node:child_process';
execSync(`psql postgres://daizu:daizu@localhost/daizu_timecard -c "DELETE FROM attendance" -c "DELETE FROM sessions"`, { stdio: 'ignore' });
// 昨日の退勤済み記録と前々月の記録を用意
execSync(`psql postgres://daizu:daizu@localhost/daizu_timecard -c "INSERT INTO attendance (work_date, staff_id, employee_id, staff_name, location_code, location_name, department, clock_in_at, clock_out_at, break_minutes, work_minutes, night_minutes, status) SELECT (now() at time zone 'Asia/Tokyo')::date - 1, id, employee_id, staff_name, 'GH01', 'GH行田', 'グループホーム', (((now() at time zone 'Asia/Tokyo')::date - 1)::text || ' 09:00+09')::timestamptz, (((now() at time zone 'Asia/Tokyo')::date - 1)::text || ' 18:00+09')::timestamptz, 60, 480, 0, 'DONE' FROM staff WHERE staff_name = '山田太郎'"`, { stdio: 'ignore' });
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, locale: 'ja-JP' });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
const shot = (n) => page.screenshot({ path: `/tmp/shots/my-${n}.png`, fullPage: true });
await page.goto('http://localhost:3000/my.html');
await page.waitForSelector('.keypad');
for (const d of ['7','7','7','7']) await page.click(`.keypad button:text-is("${d}")`);
await page.waitForSelector('input[placeholder="名前・よみがなで検索"]');
await shot('01-login');
await page.click('.item:has-text("山田太郎")');
await page.waitForSelector('.keypad');
for (const d of ['0','0','0','0']) await page.click(`.keypad button:text-is("${d}")`);
await page.waitForSelector('#app .list .item');
await shot('02-records');
await page.click('#app .list .item');
await page.waitForSelector('.modal');
await shot('03-detail');
await page.click('text=この記録を修正する');
await page.waitForSelector('.shift-form');
await page.fill('input[name="clock_out"]', '17:30');
await page.fill('textarea[name="correction_reason"]', '退勤時刻の入力ミス');
await shot('04-edit');
await page.click('.shift-form button[type=submit]');
await page.waitForSelector('.warning-box');
await shot('05-edit-warning');
await page.fill('textarea[name="reason_gh"]', '昼休憩のため');
await page.click('.shift-form button[type=submit]');
await page.waitForSelector('.toast.success');
await page.waitForTimeout(600);
await shot('06-after-edit');
// 追加（今日のまま → 確認）
await page.click('text=打刻忘れの記録を追加する');
await page.waitForSelector('.shift-form');
await page.selectOption('select[name="location_code"]', 'GH02');
await page.fill('input[name="clock_in"]', '06:00');
await page.fill('input[name="clock_out"]', '09:00');
await page.fill('textarea[name="correction_reason"]', '打刻忘れ');
await page.click('.shift-form button[type=submit]');
await page.waitForSelector('text=今日の分で間違いないので登録する');
await shot('07-add-confirm-today');
await page.click('button:has-text("閉じる")');
// 有給
await page.click('[role=tab]:has-text("有給申請")');
await page.waitForSelector('text=有給を申請する');
await shot('08-leave');
await page.click('text=有給を申請する');
await page.waitForSelector('.toast');
await shot('09-leave-done');
// 暗証番号
await page.goto('http://localhost:3000/my.html#pin'); await page.reload();
await page.waitForSelector('input[placeholder="名前・よみがなで検索"]');
await page.click('.item:has-text("山田太郎")');
await page.waitForSelector('.keypad');
await shot('10-pin');
const bodyW = await page.evaluate(() => document.documentElement.scrollWidth);
console.log('scrollWidth', bodyW, 'errors', errors);
await browser.close();
